name: Go

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go test -v ./...
        env:
          KALSHI_PASSWORD: ${{ secrets.KALSHI_PASSWORD }}
          KALSHI_EMAIL: ${{ secrets.KALSHI_EMAIL }}